extends Resource
class_name KeyBindSettings

@export var action_names: Dictionary = {}
@export var game_mode = InputEventKey.new()
@export var ui_down = InputEventKey.new()
@export var ui_up = InputEventKey.new()
@export var ui_left = InputEventKey.new()
@export var ui_right = InputEventKey.new()
@export var camera_left = InputEventKey.new()
@export var camera_right = InputEventKey.new()
@export var camera_down = InputEventKey.new()
@export var camera_up = InputEventKey.new()
@export var ui_recenter = InputEventKey.new()
@export var ui_shift = InputEventKey.new()
@export var unturtle = InputEventKey.new()
@export var FireWeapon = InputEventKey.new()
@export var weapon_change = InputEventKey.new()
@export var enter_recon = InputEventKey.new()
@export var Reverso = InputEventKey.new()
@export var CaptureCon = InputEventKey.new()
@export var halp = InputEventKey.new()
@export var HideHud = InputEventKey.new()
@export var radar_zoom = InputEventKey.new()
@export var main_menu = InputEventKey.new()
@export var take_screen_capture = InputEventKey.new()
@export var paint_target = InputEventKey.new()
@export var unpaint_target = InputEventKey.new()
@export var activate_mine = InputEventKey.new()
